<a href="https://colab.research.google.com/github/lmcanavals/machine_learning/blob/main/0703_text_vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%%file corpus.txt
saludo al sol con una sonrisa
cuando sonries se te ven los dientes
como los dientes de un sol de caricatura

Writing corpus.txt


In [6]:
with open('corpus.txt') as f:
    docs = f.readlines()

docs
m = len(docs)

In [7]:
words = list(set((' '.join(docs)).split()))
words

['se',
 'saludo',
 'dientes',
 'caricatura',
 'sonries',
 'un',
 'como',
 'de',
 'al',
 'te',
 'con',
 'sol',
 'sonrisa',
 'una',
 'los',
 'cuando',
 'ven']

In [8]:
n = len(words)
n

17

In [9]:
import numpy as np

In [10]:
X = np.zeros((m, n))
for i, doc in enumerate(docs):
    for j, word in enumerate(words):
        if word in doc:
            X[i, j] = 1

print(X)

[[0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0.]]
